import type { Trade } from "./types";

/**
 * Raw mock trades — daysSinceTrade and convictionScore are placeholders.
 * They get computed at runtime by tradeService.ts.
 */
export const rawMockTrades: Omit<Trade, "daysSinceTrade" | "convictionScore">[] = [
  // NOTE: All mock entries include `source: "mock"`.
  //       The service layer adds daysSinceTrade and convictionScore at runtime.
  // 1. Fresh high-dollar buy, self-owned, fast disclosure
  {
    id: "t-001",
    politicianName: "Nancy Pelosi",
    party: "D",
    chamber: "House",
    state: "CA",
    ticker: "NVDA",
    company: "NVIDIA Corp",
    sector: "Technology",
    type: "buy",
    amountRange: "$500,001 - $1,000,000",
    amountMidpoint: 750_000,
    ownerType: "Self",
    transactionDate: "2025-02-10",
    disclosureDate: "2025-02-18",
    daysToDisclose: 8,
    committees: ["Financial Services"],
    sectorInsight: "Tech Expansion",
    source: "mock",
  },
  // 2. 40-day delayed small buy — amber/rose lag territory
  {
    id: "t-002",
    politicianName: "Dan Crenshaw",
    party: "R",
    chamber: "House",
    state: "TX",
    ticker: "XOM",
    company: "Exxon Mobil Corp",
    sector: "Energy",
    type: "buy",
    amountRange: "$1,001 - $15,000",
    amountMidpoint: 8_000,
    ownerType: "Self",
    transactionDate: "2025-01-05",
    disclosureDate: "2025-02-14",
    daysToDisclose: 40,
    committees: ["Energy and Commerce"],
    sectorInsight: "Energy Shift",
    source: "mock",
  },
  // 3. Spouse trade — moderate amount, quick disclosure
  {
    id: "t-003",
    politicianName: "Tommy Tuberville",
    party: "R",
    chamber: "Senate",
    state: "AL",
    ticker: "MSFT",
    company: "Microsoft Corp",
    sector: "Technology",
    type: "buy",
    amountRange: "$50,001 - $100,000",
    amountMidpoint: 75_000,
    ownerType: "Spouse",
    transactionDate: "2025-02-01",
    disclosureDate: "2025-02-12",
    daysToDisclose: 11,
    committees: ["Armed Services", "Agriculture"],
    sectorInsight: "Tech Expansion",
    source: "mock",
  },
  // 4. Large sell, self-owned, very late disclosure
  {
    id: "t-004",
    politicianName: "Mark Green",
    party: "R",
    chamber: "House",
    state: "TN",
    ticker: "PFE",
    company: "Pfizer Inc",
    sector: "Healthcare",
    type: "sell",
    amountRange: "$100,001 - $250,000",
    amountMidpoint: 175_000,
    ownerType: "Self",
    transactionDate: "2024-11-15",
    disclosureDate: "2025-02-05",
    daysToDisclose: 82,
    committees: ["Homeland Security"],
    sectorInsight: "Healthcare Play",
    source: "mock",
  },
  // 5. Joint account, moderate range, moderate lag
  {
    id: "t-005",
    politicianName: "Ro Khanna",
    party: "D",
    chamber: "House",
    state: "CA",
    ticker: "GOOGL",
    company: "Alphabet Inc",
    sector: "Technology",
    type: "buy",
    amountRange: "$15,001 - $50,000",
    amountMidpoint: 32_500,
    ownerType: "Joint",
    transactionDate: "2025-01-20",
    disclosureDate: "2025-02-15",
    daysToDisclose: 26,
    committees: ["Armed Services", "Oversight"],
    sectorInsight: "Tech Expansion",
    source: "mock",
  },
  // 6. Small defense buy, self, fast disclosure
  {
    id: "t-006",
    politicianName: "Michael McCaul",
    party: "R",
    chamber: "House",
    state: "TX",
    ticker: "LMT",
    company: "Lockheed Martin Corp",
    sector: "Defense",
    type: "buy",
    amountRange: "$15,001 - $50,000",
    amountMidpoint: 32_500,
    ownerType: "Self",
    transactionDate: "2025-02-05",
    disclosureDate: "2025-02-12",
    daysToDisclose: 7,
    committees: ["Foreign Affairs", "Homeland Security"],
    sectorInsight: "Defense & Security",
    source: "mock",
  },
  // 7. Senate finance sell, spouse, moderate lag
  {
    id: "t-007",
    politicianName: "Sheldon Whitehouse",
    party: "D",
    chamber: "Senate",
    state: "RI",
    ticker: "JPM",
    company: "JPMorgan Chase & Co",
    sector: "Finance",
    type: "sell",
    amountRange: "$50,001 - $100,000",
    amountMidpoint: 75_000,
    ownerType: "Spouse",
    transactionDate: "2025-01-10",
    disclosureDate: "2025-02-20",
    daysToDisclose: 41,
    committees: ["Budget", "Judiciary"],
    sectorInsight: "Banking Bet",
    source: "mock",
  },
  // 8. Mega buy, self, timely — highest conviction scenario
  {
    id: "t-008",
    politicianName: "Josh Gottheimer",
    party: "D",
    chamber: "House",
    state: "NJ",
    ticker: "AMZN",
    company: "Amazon.com Inc",
    sector: "Technology",
    type: "buy",
    amountRange: "$1,000,001+",
    amountMidpoint: 5_000_000,
    ownerType: "Self",
    transactionDate: "2025-02-15",
    disclosureDate: "2025-02-20",
    daysToDisclose: 5,
    committees: ["Financial Services"],
    sectorInsight: "Tech Expansion",
    source: "mock",
  },
  // 9. Real estate play, joint, slow disclosure
  {
    id: "t-009",
    politicianName: "Dianne Feinstein",
    party: "D",
    chamber: "Senate",
    state: "CA",
    ticker: "AMT",
    company: "American Tower Corp",
    sector: "Real Estate",
    type: "buy",
    amountRange: "$250,001 - $500,000",
    amountMidpoint: 375_000,
    ownerType: "Joint",
    transactionDate: "2024-12-01",
    disclosureDate: "2025-02-10",
    daysToDisclose: 71,
    committees: ["Appropriations", "Intelligence"],
    sectorInsight: "Property Move",
    source: "mock",
  },
  // 10. Small utility buy, self, moderate lag — low conviction
  {
    id: "t-010",
    politicianName: "Bill Cassidy",
    party: "R",
    chamber: "Senate",
    state: "LA",
    ticker: "NEE",
    company: "NextEra Energy Inc",
    sector: "Utilities",
    type: "buy",
    amountRange: "$1,001 - $15,000",
    amountMidpoint: 8_000,
    ownerType: "Self",
    transactionDate: "2025-01-15",
    disclosureDate: "2025-02-18",
    daysToDisclose: 34,
    committees: ["Finance", "Health"],
    sectorInsight: "Utilities Play",
    source: "mock",
  },
];
